"""flashcard table

Revision ID: 6203d7583441
Revises: e9a9f94c28e1
Create Date: 2018-05-23 12:01:03.456717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6203d7583441'
down_revision = 'e9a9f94c28e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('front', sa.String(length=5000), nullable=True),
    sa.Column('back', sa.String(length=5000), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_timestamp'), 'flashcard', ['timestamp'], unique=False)
    op.drop_index('ix_fraudprediction_timestamp', table_name='fraudprediction')
    op.drop_table('fraudprediction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraudprediction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('data', sa.VARCHAR(length=30000), nullable=True),
    sa.Column('prediction', sa.NUMERIC(precision=1, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fraudprediction_timestamp', 'fraudprediction', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_flashcard_timestamp'), table_name='flashcard')
    op.drop_table('flashcard')
    # ### end Alembic commands ###
