"""flashcard rem timestamp index

Revision ID: 7d6cb8903f7e
Revises: 6203d7583441
Create Date: 2018-05-24 06:59:12.369796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6cb8903f7e'
down_revision = '6203d7583441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flashcard_timestamp', table_name='flashcard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_flashcard_timestamp', 'flashcard', ['timestamp'], unique=False)
    # ### end Alembic commands ###
