"""fraudpredictiontable

Revision ID: e9a9f94c28e1
Revises: f2e6979f579f
Create Date: 2018-05-17 13:46:14.883275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a9f94c28e1'
down_revision = 'f2e6979f579f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraudprediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('data', sa.String(length=30000), nullable=True),
    sa.Column('prediction', sa.Numeric(precision=1, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraudprediction_timestamp'), 'fraudprediction', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fraudprediction_timestamp'), table_name='fraudprediction')
    op.drop_table('fraudprediction')
    # ### end Alembic commands ###
